modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "catchindicator"
version = "${version}"
displayName = "Catch Indicator"
logoFile="assets/catchindicator/logo.png"
authors = "OurStory x LevelsFR"
description = '''
Shows a small indicator next to wild Pokémon names based on your Pokédex status (caught, seen, unknown).
'''
#logoFile="assets/ourstorymulti_example/icon.png"

[[mixins]]
config="catchindicator-common.mixins.json"

[[mixins]]
config="catchindicator-neoforge.mixins.json"
